### ISSUE TITLE
comment symbol # in a code block is mistakenly recognized as a heading

### ISSUE THREAD

**Issue by hopezh** [AntonVanAssche/md-headers.nvim#1]
As shown below, the comment symbol # is recognized as a heading, when it should be excluded. 

![image](https://github.com/AntonVanAssche/md-headers.nvim/assets/23435810/25301b3e-bc58-47b0-a713-7d3191369903)

**Comment by AntonVanAssche** [comment]
Hi @hopezh

First of all, thanks for reporting this issue. I have looked into the issue, and found the root cause of it.

Currently, the plugin uses regular expressions to detect headings in the markdown file. While this approach is simple, it can sometimes misinterpret certain symbols, such as the '#' symbol in code blocks, as headings. This happens because the regular expression pattern used for detecting headings is not aware of the context in which the '#' symbol appears.

To address this issue and improve the overall accuracy of heading detection, I'm working on a more robust solution using Neovim's treesitter functionality. Treesitter provides a powerful parsing mechanism that can better understand the structure and context of code and markup languages. By leveraging treesitter, we can avoid such false positives and ensure accurate identification of headings, even within code blocks.

I've already made progress in this direction and have a working solution that correctly identifies markdown headings. However, I'm still working on refining it to handle HTML headings as well, as extracting them from the file is more complex. Meaning no HTML headings will be shown in the list at the moment.

Best regards,
Anton

**Comment by AntonVanAssche** [comment]
I just fixed the closest header functionality for the markdown headers (https://github.com/AntonVanAssche/md-headers.nvim/commit/1779a27949b3e8467a7507ea6b6d289bb77c0a42), now it's a matter of finding the right query for the html headers. Once I have it it shouldn't be too hard to implement. After that it's just sorting the table and returning it.

**Comment by hopezh** [comment]
> I just fixed the closest header functionality for the markdown headers ([1779a27](https://github.com/AntonVanAssche/md-headers.nvim/commit/1779a27949b3e8467a7507ea6b6d289bb77c0a42)), now it's a matter of finding the right query for the html headers. Once I have it it shouldn't be too hard to implement. After that it's just sorting the table and returning it.

Thank you very much. Looking forward to the release of these latest updates.

**Comment by AntonVanAssche** [comment]
Issue resolved, see https://github.com/AntonVanAssche/md-headers.nvim/commit/28783382cf22618f0d0df1658727bb7eecf213ce.
