### ISSUE TITLE
Is there a way to make the plugin work with .rmd files for RMarkdown?

### ISSUE THREAD

**Issue by MarcoCamilo** [AntonVanAssche/md-headers.nvim#7]
Since RMarkdown uses the same syntax for headings, I was hoping to know if there's a way to configure the plugin currently so that it's also triggered in .rmd files. I'm currently using LazyVim for my plugin management.

**Comment by AntonVanAssche** [comment]
Hi @MarcoCamilo,

Thank you for bringing this to my attention. I agree that it would be beneficial to have the plugin work seamlessly with RMarkdown files as well. To address this, you can try making a small modification to the plugin code.

You can attempt this by adding the `.rmd` extension to the pattern variable in the following file: [md-headers.lua](https://github.com/AntonVanAssche/md-headers.nvim/blob/master/plugin/md-headers.lua), like shown below.

```lua
-- Check whether the plugin is already loaded.
if _G.loaded_md_headers then
    return
end

-- Assig the MarkdownHeaders command when entering a buffer
-- containing a Markdown file.
vim .api.nvim_create_autocmd(
    'BufWinEnter', {
    pattern = {
        '*.md',
        '*.rmd'
    },
    callback = function()
        vim.api.nvim_create_user_command('MarkdownHeaders', function()
            require('md-headers').markdown_headers(false)
        end, {})
    end
})

vim .api.nvim_create_autocmd(
    'BufWinEnter', {
    pattern = {
        '*.md',
        '*.rmd'
    },
    callback = function()
        vim.api.nvim_create_user_command('MarkdownHeadersClosest', function()
            require('md-headers').markdown_headers(true)
        end, {})
    end
})

-- Set the plugin as loaded.
_G.loaded_md_headers = true
```

I'll work on implementing this enhancement as soon as possible, likely later today. In the meantime, feel free to test it out locally by editing the file. For Packer users, the file is often located at `~/.local/share/nvim/site/pack/packer/start/md-headers.nvim/plugin/md-headers.lua`. However, since you're using LazyVim, the equivalent path might be different. Please check your LazyVim setup for the precise location.

Let me know if you encounter any issues or if you have further questions.

Kindest regards,
Anton

**Comment by AntonVanAssche** [comment]
Great news! After some testing and tweaking, it seems that the enhancement for RMarkdown files works as expected. You can see the successful test in the screenshot below:

![image](https://github.com/AntonVanAssche/md-headers.nvim/assets/61730941/4f95913f-1cf1-4c9e-abe3-1cadca065e7f)

I've gone ahead and initiated a Pull Request to merge these changes into the master branch. Before finalizing it, I'd appreciate it if you could also test and share your experience. If everything looks good on your end and there are no issues, we can proceed with merging this enhancement.

Feel free to reply here or on the Pull Request with any feedback or concerns.

Thank you for your patience and collaboration!

**Comment by AntonVanAssche** [comment]
Issue resolved, see: https://github.com/AntonVanAssche/md-headers.nvim/commit/97653a16e01308fbcf6997353ca3fa4861227e98.
